### ISSUE TITLE
Steps for Development

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/background-revolution#1]
Part 1:

- [x] Have a button on GUI to open file explorer and select an image for the background.
- [x] try to open image, return an error message if unsupported file type inside image box.  (not needed since configured file types already)
- [x] Display image on GUI to review the image and submit. 
- [x] Change the user's background to the selected image upon hitting the submit button. 
- [ ] Could add options like this for how the image appears (fill = default, could also add resizing with whitespace on sides, could recommend tile for smaller images which would lose out on quality upon resizing to fill screen)
![image](https://user-images.githubusercontent.com/53918934/126876007-9efc65fe-4aa3-4a48-86f2-06886f1eb6ea.png)

Part 2:

- [ ] Uploading a custom collection of backgrounds, being able to upload multiple at a time
- [ ] Being able to configure which images are in a current rotation and the period for which it is present in the cycle.
- [ ] Schedule pictures for the next x amount of time to rotate through, until let's say 9 months is done with 36 cars images, 1 for every week. 
- [ ] Get time from user's computer or have a server running, probably the latter.

Part 3:

- [ ] Webscrape images for custom searches by users themselves through google images (google images API).
- [ ] Can also choose custom collections or some preset options (that we've picked). 
- [ ] Can choose which preset collections of ours to show by putting them in a checkbox grid type thing.

**Comment by Daggerpov** [comment]
@StephenRebel what does the third bullet point under Part 2 mean?

**Comment by StephenRebel** [comment]
@Daggerpov A sort of idea If we add a prebuilt in bank of images, the user could be able to select the type they’d like to view

**Comment by Daggerpov** [comment]
> @Daggerpov A sort of idea If we add a prebuilt in bank of images, the user could be able to select the type they’d like to view

![image](https://user-images.githubusercontent.com/53918934/126030387-97eab339-95e7-473d-be6c-3d17acd28420.png)
 that's what this means though right? I think we should make this as part of the 3rd part.
